# Python for PoF - Workshop Series - Part 1.3

Vamsi Spandan

Dennis Bakhuis

**Reference Material** : 
* Effective Computation in Physics, Anthony Scopatz, Kathryn Huff, O'Reilly Media.
* Python for Scientists, John Stewar, Cambridge.

## Why Numpy

In [11]:
def func_py(N):
    x = 0.0
    for i in range(N):
        x += (x%2 - 1)*i
    return x

In [12]:
%timeit func_py(10000)

100 loops, best of 3: 2.41 ms per loop


Same function can easily be implemented in Fortran or C

In [16]:
# %install_ext https://raw.github.com/mgaitan/fortran_magic/master/fortranmagic.py

# conda install -c conda-forge fortran-magic=0.7


In [17]:
%load_ext fortranmagic

/Users/arzavs/anaconda/lib/python3.5/site-packages/IPython/utils/path.py:264: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module
  warn("get_ipython_cache_dir has moved to the IPython.paths module")


In [18]:
%%fortran
subroutine func_fort(n,d)
    integer, intent(in) :: n
    double precision, intent(out) :: d
    integer :: i
    d = 0
    do i = 0, n-1
        d = d + (mod(i,3)-1)*i
    end do
end subroutine func_fort

In [19]:
%timeit func_fort(10000)

100000 loops, best of 3: 15.1 µs per loop


## 1. NumPy

NumPy gets us best of both worlds !

Many useful functions are not in the Python built in library, but are in external
scientific packages. These need to be imported into your Python notebook (or program) before
they can be used. Probably the most important of these are numpy and matplotlib.

Numpy is the bread of scientific computing. It can offer performance close to that of compiled languages but with the ease of the Python language. 

If `a` and `b` are two Python lists of the the same size and you want to multiply them element-wise. 

*Using Lists*
```
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
```
*Using C*
``` 
for(i=0; i<rows; i++) {
    c[i]=a[i]*b[i]:
}
```

*Using Numpy*
```
c = a*b
```

In [ ]:
# Many useful functions are in external packages
# Let's meet numpy
import numpy as np

In [ ]:
# Tab completion to see what is available


In [ ]:
# This function looks for the string the in docstrings of all 
# numpy functions
np.lookfor('cosine')

In [ ]:
# To see what's in a package, type the name, a period, then hit tab
#np?
np.arange?

In [ ]:
# Some examples of numpy functions and "things"
print(np.sqrt(4))
print(np.pi)  # Not a function, just a variable
print(np.sin(np.pi))

###  Numpy arrays (ndarrays)
Numpy arrays are collections of things, all of which must be the same type, that work similarly to lists (but not exactly). The most important are:

1. You can easily perform elementwise operations (and matrix algebra) on arrays
1. Arrays can be n-dimensional
1. There is no equivalent to append, although arrays can be concatenated

Arrays can be created from existing collections such as lists, or instantiated "from scratch" in a 
few useful ways.

When getting started with scientific Python, you will probably want to try to use ndarrays whenever
possible, saving the other types of collections for those cases when you have a specific reason to use
them.

In [ ]:
# We need to import the numpy library to have access to it 
# We can also create an alias for a library, this is something you will commonly see with numpy
import numpy as np

# Make an array from a list
alist = [2, 3, 4]
blist = [5, 6, 7]
a = np.array(alist)
b = np.array(blist)
print(a, type(a))
print(b, type(b))

In [ ]:
# Do arithmetic on arrays
print(a**2)
print(np.sin(a))
print(a * b)
print(a.dot(b), np.dot(a, b))

In [ ]:
# Boolean operators work on arrays too, and they return boolean arrays
print(a > 2)
print(b == 6)

c = a > 2
print(c)
print(type(c))
print(c.dtype)

In [ ]:
# There are handy ways to make arrays full of ones and zeros
print(np.zeros(5))
print ('\n')
print(np.ones(5), '\n')
print(np.identity(5), '\n')

In [ ]:
# You can also easily make arrays of number sequences
print(np.arange(0, 10, 2))

print(np.linspace(0,10,num=5))

**Masking**


In [30]:
a = np.array([1,3,4,5,6,7,8])
print(a[a>4])

[5 6 7 8]


In [32]:
a = np.array([1,2,3,4])
my_mask = np.array([False,True,True,False])

a[my_mask]

array([2, 3])

**Numpy for Matlab users**

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

http://mathesaurus.sourceforge.net/matlab-numpy.html

In [ ]:
# Arithmetic element-wise operations on arrays of same size
a = np.linspace(0,1,5)
b = np.linspace(1,3,5)

print(a+b)
print(a*b)
print(a/b)

**Vectorized code executes faster**

In [7]:
# Smooth data by three-point averaging
f = np.sin(np.linspace(0,1,1000000))
f_av = f.copy()
f_av[1:-1]=(f[:-2]+f[1:-1]+f[2:])/3.0

%timeit

**Get rid of simple python loops in your code**
https://www.youtube.com/watch?v=EEUXKG97YRw

Some strategies

*__1.Use ufuncs (universal functions)__*

They operate element wise on arrays

In [ ]:
a = [1,2,3,4,5,6]
b = [val + 5 for val in a]
print (b)

In [ ]:
a = np.array(a)
b = a + 5
print(b)

In [20]:
a = list(range(100000))
%timeit [val+5 for val in a]

100 loops, best of 3: 5.97 ms per loop


In [21]:
a = np.array(a)
%timeit a+5

10000 loops, best of 3: 68.3 µs per loop


There are many ufuncs available. 
- Arithmetic
- Bitwise operators
- Comparison operators
- Trignometry family : np.sin, np.cos
- Exponential family : np.exp, np.log, 
- Special functions  : scipy.special.* [Bessel functions, Gamma functions]

**__2.Numpy aggregations__**

They summarise the information on arrays. Such as minimum, maximum, mean etc. 

In [25]:
print(a.max(), a.min(), a.mean(), a.std())

99999 0 49999.5 28867.513458


In [29]:
M = np.random.randint(0,10,(3,5))
M

array([[5, 9, 4, 2, 8],
       [4, 3, 3, 8, 1],
       [3, 0, 2, 8, 2]])

In [28]:
M.sum()

84

In [ ]:
M.sum(axis=0) # sum of columns in the array

In [ ]:
M.sum(axis=1) # sum of rows in the array

** Numpy text output and input **

In [33]:
len = 21
x = np.linspace(0,2*np.pi,len)
c = np.cos(x)
s = np.sin(x)
t = np.tan(x)

arr = np.empty((4,len),dtype=float)
arr[0,:] = x
arr[1,:] = c
arr[2,:] = s
arr[3,:] = t

np.savetxt('x.txt',x)
np.savetxt('xcst.txt', (x,c,s,t))
np.savetxt('xarr.txt',arr)

In [34]:
xc = np.loadtxt('x.txt')
xc,cc,sc,tc = np.loadtxt('xcst.txt')
arrc = np.loadtxt('xarr.txt')

Writing and reading binary files is faster and produce more compact files because conversion to and from text is not needed. However, they cannot be read by humans. 

Numpy has its own binary format which guarantees paltform independence. You can save single arrays and also multiple arrays of different shapes

You can also load data from other programs (*.mat) (*.hdf5) etc.

In [36]:
# For a single vector or array
np.save('array.npy',arr)

arrc = np.load('array.npy')

In [37]:
# For different arrays - use a zipped binary archive
np.savez('test.npz', x=x, c=c, s=s, t=t)

# Recovering is a two step process
temp = np.load('test.npz')
xc = temp['x']
cc = temp['c']
sc = temp['s']
tc = temp['t']

## 2. Graphics

Welcome Matplotlib ! (http://matplotlib.org/gallery.html)

In [42]:
import matplotlib.pyplot as plt


In [47]:
x = np.linspace(-np.pi,np.pi,101)
y = np.sin(x)+np.sin(3*x)/3.0

plt.plot(x,y)
plt.savefig('foo.pdf')
plt.show()